packaging_format = 2

id = "homer"
name = "Homer"
description.en = "Simple static homepage for your server"
description.fr = "Page d'accueil simpliste pour votre serveur"

version = "21.09.2~ynh1"

maintainers = ["Salamandar"]

[upstream]
license = "MIT"
demo = "https://homer-demo.netlify.app/"
admindoc = "https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md"
userdoc = "https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md"
code = "https://github.com/bastienwirtz/homer"
website = "https://github.com/bastienwirtz/homer"
cpe = "???" # FIXME: optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is sort of a standard id for applications defined by the NIST. In particular, Yunohost may use this is in the future to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search. For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
fund = "???" # FIXME: optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.

[integration]
yunohost = ">= 11.2"
architectures = "all" # FIXME: can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386"]
multi_instance = true
ldap = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
sso = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "path"
    default = "/homer"

    [install.init_main_permission]
    type = "group"
    default = false

[resources]
        [resources.sources.main]
        url = "https://github.com/bastienwirtz/homer/releases/download/v21.09.2/homer.zip"
        sha256 = "347bc7dc85b4e4ed58bcfa7428e514d1a8d9b2e87b04c82a51326f3306dcfaa6"
        in_subdir = false


    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
